#Rename to settings.yml and set propper values

disqus.audsync.publickey: ~
disqus.audsync.secret: ~
disqus.audsync.accesstokenurl: ~

disqus.forumname: ~
disqus.basesiteurl: ~ # Must match the configured forum domain (even if it's localhost)

disqus.audsync.debug.accesstoken: ~ # Your access token from your Disqus Application (for testing porpouses)

mysql:
  host: ~
  username: ~
  password: ~
  database: ~