#Rename to settings.yml and set propper values

disqus.audsync.publickey: ~
disqus.audsync.secret: ~
disqus.audsync.accesstokenurl: ~

disqus.forumname: ~
disqus.basesiteurl: ~ # Must match the configured forum domain (even if it's localhost)