#Rename to settings.yml and set propper values

disqus.audsync.publickey: ~
disqus.audsync.secret: ~
disqus.audsync.accesstokenurl: ~
disqus.audsync.redirect_uri: ~ # Only used if you invoke the Audience Sync login manually by using DisqusOAuthManager->getAudienceSyncAuthorizationURL()

disqus.forumname: ~
disqus.basesiteurl: ~ # Must match the configured forum domain (even if it's localhost)

mysql:
  host: ~
  username: ~
  password: ~
  database: ~