#!/usr/bin/env php
<?php

set_time_limit(0);

$app = require_once __DIR__.'/../web/index.php';

$application = $app['console'];
$application->add(new TFT\Commands\SchemaCommand());
$application->run();

?>